import cv2
import numpy as np
from PIL import Image, ExifTags
import struct
import zlib
import re
import os

# ─── Assinaturas de modelos de IA conhecidos ────────────────────────────────
AI_TOOL_SIGNATURES = [
    # Stable Diffusion / ComfyUI / Automatic1111
    "steps:", "sampler:", "cfg scale:", "cfg_scale:", "seed:", "negative prompt:",
    "negative_prompt:", "model hash:", "model_hash:", "sdxl", "stable diffusion",
    "comfyui", "automatic1111", "a1111", "invokeai", "novelai",
    # Midjourney
    "midjourney", "--ar ", "--q ", "--v ", "--s ", "--niji",
    # DALL-E / OpenAI
    "dall-e", "dall_e", "openai", "gpt-4o",
    # Adobe Firefly / Photoshop AI
    "adobe firefly", "generative fill", "adobe ai",
    # Google / Meta
    "imagen", "emu", "seggpt", "meta ai",
    # Runway / Pika / Kling
    "runway", "gen-2", "gen-3", "pika labs", "kling",
    # Luma / Ideogram
    "luma ai", "ideogram", "canva ai",
    # Watermark tokens comuns
    "ai generated", "generated by ai", "artificial intelligence generated",
    "created with ai", "ai art", "aiart",
    # Parâmetros genéricos de geração
    "prompt:", "loras:", "lora:", "vae:", "checkpoint:", "denoise:",
    "guidance_scale:", "num_inference_steps:",
]

# ─── Assinaturas binárias de ferramentas de IA (magic bytes / strings fixas) ─
BINARY_AI_SIGNATURES = [
    b"MidJourney",
    b"midjourney",
    b"DALL-E",
    b"dall-e",
    b"StableDiffusion",
    b"stable-diffusion",
    b"ComfyUI",
    b"comfyui",
    b"NovelAI",
    b"novelai",
    b"InvokeAI",
    b"invokeai",
    b"Automatic1111",
    b"ai-generated",
    b"AI_GENERATED",
    b"adobe:firefly",
    b"firefly:generative",
    b"contentcredentials",  # C2PA / Content Credentials
    b"c2pa",
    b"c2pa.org",
    b"cai-store",           # Content Authenticity Initiative
    b"cai.store",
    b"cawg",               # Coalition for Content Provenance
    b"<stEvt:softwareAgent>MidJourney",
    b"<photoshop:GenerativeAI>",
]

# ─── Softwares de edição que indicam IA ──────────────────────────────────────
AI_SOFTWARE_KEYWORDS = [
    "midjourney", "dall-e", "dall_e", "stable diffusion", "stablediffusion",
    "comfyui", "novelai", "invokeai", "automatic1111", "a1111",
    "adobe firefly", "firefly", "generative", "emu", "imagen",
    "runway", "pika", "ideogram", "openai",
]


class AIDetector:

    # ─────────────────────────────────────────────────────────────────────────
    # 1. METADADOS EXIF / XMP / IPTC
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def extract_metadata(image_path: str) -> dict:
        result = {"has_metadata": False, "software": None, "xmp_data": None, "all_tags": {}}
        try:
            img = Image.open(image_path)

            # EXIF
            exif_data = img._getexif()
            if exif_data:
                result["has_metadata"] = True
                for tag_id, value in exif_data.items():
                    tag = ExifTags.TAGS.get(tag_id, str(tag_id))
                    result["all_tags"][tag] = str(value)[:300]
                    if tag == "Software":
                        result["software"] = str(value)

            # XMP / APP1 block (Pillow stores in info dict)
            if "xmp" in img.info:
                xmp_bytes = img.info["xmp"]
                xmp_str = xmp_bytes.decode("utf-8", errors="ignore") if isinstance(xmp_bytes, bytes) else str(xmp_bytes)
                result["xmp_data"] = xmp_str[:2000]

            # PNG info chunks (tEXt, iTXt, zTXt)
            if img.format == "PNG":
                for key, value in img.info.items():
                    if isinstance(value, (str, bytes)):
                        val = value.decode("utf-8", errors="ignore") if isinstance(value, bytes) else value
                        result["all_tags"][f"png:{key}"] = val[:300]

        except Exception as e:
            result["error"] = str(e)
        return result

    # ─────────────────────────────────────────────────────────────────────────
    # 2. BUSCA BINÁRIA PROFUNDA — varre bytes brutos da imagem
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def deep_binary_scan(image_path: str) -> list:
        findings = []
        try:
            with open(image_path, "rb") as f:
                raw = f.read()

            # Busca por assinaturas binárias conhecidas
            for sig in BINARY_AI_SIGNATURES:
                if sig.lower() in raw.lower():
                    findings.append(f"🔴 Assinatura binária de IA encontrada: '{sig.decode('utf-8', errors='ignore')}'")

            # Busca por strings legíveis no binário (simula `strings`)
            # Extrai sequências ASCII >= 6 chars
            readable = re.findall(rb'[ -~]{6,}', raw)
            for chunk in readable:
                decoded = chunk.decode("ascii", errors="ignore").lower()
                for sig in AI_TOOL_SIGNATURES:
                    if sig.lower() in decoded:
                        short = chunk.decode("ascii", errors="ignore")[:120]
                        entry = f"📦 Código AI encontrado no binário: '{short.strip()}'"
                        if entry not in findings:
                            findings.append(entry)
                        break

        except Exception as e:
            findings.append(f"Erro na leitura binária: {str(e)}")
        return findings

    # ─────────────────────────────────────────────────────────────────────────
    # 3. C2PA / CONTENT CREDENTIALS (Adobe, Microsoft, OpenAI padrão)
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def check_c2pa(image_path: str) -> list:
        findings = []
        try:
            with open(image_path, "rb") as f:
                raw = f.read()

            c2pa_markers = [b"c2pa", b"cai-store", b"cawg", b"contentcredentials",
                            b"jumbf", b"jumb", b"c2ma", b"c2cl", b"c2as", b"c2cs"]
            found_any = False
            for marker in c2pa_markers:
                if marker in raw.lower():
                    if not found_any:
                        findings.append("🏷️ C2PA / Content Credentials detectado: Este arquivo contém metadados de proveniência de conteúdo (padrão usado por Adobe, Microsoft, OpenAI e Midjourney para marcar imagens de IA)")
                        found_any = True

            # Verifica JFIF / JPEG markers APP11 (0xFFEB) — bloco C2PA em JPEG
            if raw[:2] == b'\xff\xd8':  # JPEG
                i = 2
                while i < len(raw) - 4:
                    if raw[i] == 0xFF and raw[i+1] == 0xEB:  # APP11 marker
                        findings.append("🔏 Bloco APP11 (JPEG) encontrado — usado para Content Credentials / C2PA em imagens DALL-E 3 e Adobe Firefly")
                        break
                    marker_len = struct.unpack(">H", raw[i+2:i+4])[0] if i+4 <= len(raw) else 0
                    i += 2 + marker_len
                    if i > 100000:
                        break

        except Exception:
            pass
        return findings

    # ─────────────────────────────────────────────────────────────────────────
    # 4. ANÁLISE DE CHUNKS PNG — verifica chunks não-padrão
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def analyze_png_chunks(image_path: str) -> list:
        findings = []
        try:
            with open(image_path, "rb") as f:
                raw = f.read()

            if raw[:8] != b'\x89PNG\r\n\x1a\n':
                return findings  # Não é PNG

            i = 8
            non_standard_chunks = []
            ai_chunk_types = {
                b"tEXt", b"iTXt", b"zTXt",   # Texto — onde SD e ComfyUI guardam prompts
                b"eXIf",                        # EXIF em PNG
                b"iCCP",                        # ICC Profile
                b"pHYs",                        # Resolução (indicador de geração)
                b"cHRM", b"gAMA",
            }

            while i < len(raw) - 12:
                length = struct.unpack(">I", raw[i:i+4])[0]
                chunk_type = raw[i+4:i+8]
                chunk_data = raw[i+8:i+8+length]
                i += 12 + length

                if chunk_type in (b"tEXt", b"iTXt", b"zTXt"):
                    try:
                        if chunk_type == b"zTXt":
                            # Decompress
                            sep = chunk_data.index(b'\x00')
                            keyword = chunk_data[:sep].decode("latin-1")
                            compressed = chunk_data[sep+2:]
                            text = zlib.decompress(compressed).decode("utf-8", errors="ignore")
                        elif chunk_type == b"iTXt":
                            sep = chunk_data.index(b'\x00')
                            keyword = chunk_data[:sep].decode("latin-1")
                            text = chunk_data[sep:].decode("utf-8", errors="ignore")
                        else:
                            sep = chunk_data.index(b'\x00')
                            keyword = chunk_data[:sep].decode("latin-1")
                            text = chunk_data[sep+1:].decode("latin-1", errors="ignore")

                        text_lower = text.lower()
                        for sig in AI_TOOL_SIGNATURES:
                            if sig.lower() in text_lower:
                                short_text = text[:200].replace('\n', ' ')
                                findings.append(f"📝 Chunk PNG '{chunk_type.decode()}' (chave: '{keyword}'): '{short_text}...'")
                                break
                    except Exception:
                        pass

                # Chunks não-padrão podem conter dados ocultos
                if chunk_type not in {b"IHDR", b"IDAT", b"IEND", b"tEXt", b"iTXt",
                                       b"zTXt", b"cHRM", b"gAMA", b"iCCP", b"sRGB",
                                       b"bKGD", b"hIST", b"tIME", b"pHYs", b"sPLT",
                                       b"eXIf"} and len(chunk_type) == 4:
                    ctype_str = chunk_type.decode("ascii", errors="ignore")
                    if ctype_str.isalpha():
                        non_standard_chunks.append(ctype_str)

            if non_standard_chunks:
                findings.append(f"⚠️ Chunks PNG não-padrão detectados (possível dados ocultos): {', '.join(set(non_standard_chunks))}")

        except Exception:
            pass
        return findings

    # ─────────────────────────────────────────────────────────────────────────
    # 5. DETECÇÃO ESTATÍSTICA — Análise de frequência DCT / LSB
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def analyze_statistical_artifacts(image_path: str) -> dict:
        result = {"lsb_uniformity": 0.0, "dct_score": 0.0, "color_palette_size": 0, "notes": []}
        try:
            img_pil = Image.open(image_path).convert("RGB")
            img_np = np.array(img_pil)

            # ── LSB Analysis: imagens de IA têm LSBs mais uniformes
            lsb_plane = img_np[:, :, 0] & 1  # Canal R, bit 0
            lsb_mean = float(np.mean(lsb_plane))
            # Próximo de 0.5 = noise aleatório (real). Muito baixo ou alto = suspeito
            result["lsb_uniformity"] = float(round(abs(lsb_mean - 0.5) * 200, 1))  # 0-100

            # ── DCT Analysis via OpenCV (frequências altas em imagens de IA são diferentes)
            img_gray = cv2.cvtColor(img_np, cv2.COLOR_RGB2GRAY).astype(np.float32)
            dct = cv2.dct(img_gray)
            # Alto nível de energia em frequências médias = possível geração sintética
            h, w = dct.shape
            mid_energy = float(np.sum(np.abs(dct[h//8:h//2, w//8:w//2])))
            total_energy = float(np.sum(np.abs(dct))) + 1e-10
            result["dct_score"] = float(round((mid_energy / total_energy) * 100, 1))

            # ── Color Palette Analysis: IA tende a ter paletas mais uniformes
            small = img_pil.resize((64, 64))
            colors = small.getcolors(maxcolors=4096)
            result["color_palette_size"] = int(len(colors)) if colors else 4096

            # ── Laplacian variance (texturas suaves = IA)
            lap_var = float(cv2.Laplacian(img_gray.astype(np.uint8), cv2.CV_64F).var())
            result["laplacian_variance"] = float(round(lap_var, 2))

            if result["lsb_uniformity"] > 30:
                result["notes"].append(f"Distribuição de LSB anormal ({result['lsb_uniformity']:.1f}%) — possível watermark ou imagem sintética")
            if result["dct_score"] > 60:
                result["notes"].append(f"Energia DCT em frequências médias elevada ({result['dct_score']:.1f}%) — padrão típico de geração por diffusion model")
            if lap_var < 50 and lap_var > 0:
                result["notes"].append("Texturas anormalmente suaves (variância laplaciana baixa) — característico de imagens de IA")
            elif lap_var > 1500:
                result["notes"].append("Nitidez sintética excessiva — possível pós-processamento por IA (upscaling)")

        except Exception as e:
            result["notes"].append(f"Erro na análise estatística: {str(e)}")
        return result

    # ─────────────────────────────────────────────────────────────────────────
    # 6. VERIFICAÇÃO DE METADADOS EXTENDIDOS (tudo)
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def check_all_metadata_fields(image_path: str) -> list:
        findings = []
        try:
            meta = AIDetector.extract_metadata(image_path)

            # Varredura em todos os campos
            all_text = ""
            for key, value in meta.get("all_tags", {}).items():
                val_lower = str(value).lower()
                for sig in AI_TOOL_SIGNATURES:
                    if sig.lower() in val_lower:
                        findings.append(f"🏷️ Metadado '{key}': encontrou assinatura de IA → '{str(value)[:150]}'")
                        break
                all_text += f" {value}"

            # Verificação no bloco XMP
            xmp = meta.get("xmp_data", "") or ""
            xmp_lower = xmp.lower()
            xmp_ai_hits = []
            for sig in AI_TOOL_SIGNATURES + ["generatorengineid", "generatorenginename", "aiartifact",
                                               "firefly", "photoshop:generatedfill", "iptc:digitalsourcetype"]:
                if sig.lower() in xmp_lower:
                    xmp_ai_hits.append(sig)

            if xmp_ai_hits:
                findings.append(f"📄 Bloco XMP contém {len(xmp_ai_hits)} indicadores de IA: {', '.join(xmp_ai_hits[:8])}")

            # Software field check
            software = meta.get("software", "") or ""
            if software:
                sw_lower = software.lower()
                for kw in AI_SOFTWARE_KEYWORDS:
                    if kw in sw_lower:
                        findings.append(f"💻 Software de IA identificado no EXIF: '{software}'")
                        break

        except Exception as e:
            pass
        return findings

    # ─────────────────────────────────────────────────────────────────────────
    # 7. ANÁLISE DE RESOLUÇÃO + PROPORÇÃO (padrões de geradores de IA)
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def check_ai_resolution(image_path: str) -> list:
        findings = []
        # Resoluções exatas de geradores conhecidos
        ai_resolutions = {
            (512, 512): "Stable Diffusion v1.x (padrão)",
            (768, 768): "Stable Diffusion 2.x",
            (1024, 1024): "DALL-E 3 / SDXL / Midjourney (1:1)",
            (1024, 1536): "DALL-E 3 / Midjourney (2:3 retrato)",
            (1536, 1024): "DALL-E 3 / Midjourney (3:2 paisagem)",
            (1024, 1792): "DALL-E 3 (9:16 retrato)",
            (1792, 1024): "DALL-E 3 (16:9 paisagem)",
            (1280, 720): "Runway Gen-2 / Pika (16:9)",
            (1920, 1080): "Runway Gen-3 / Kling (16:9 HD)",
            (832, 1216): "SDXL (2:3)",
            (1216, 832): "SDXL (3:2)",
            (896, 1152): "SDXL",
            (1152, 896): "SDXL",
            (640, 1536): "SDXL tall",
            (1536, 640): "SDXL wide",
        }
        try:
            with Image.open(image_path) as img:
                w, h = img.size
                if (w, h) in ai_resolutions:
                    findings.append(f"📐 Resolução exata de gerador de IA: {w}×{h} — {ai_resolutions[(w, h)]}")
                else:
                    # Verifica se é múltiplo de 64 (todas as redes de diffusion usam isso)
                    if w % 64 == 0 and h % 64 == 0 and w >= 512 and h >= 512:
                        # Verifica aspect ratios comuns de IA
                        gcd = np.gcd(w, h)
                        ar_w, ar_h = w // gcd, h // gcd
                        ai_ratios = [(1, 1), (4, 3), (3, 4), (16, 9), (9, 16), (2, 3), (3, 2)]
                        if (ar_w, ar_h) in ai_ratios:
                            findings.append(f"📐 Resolução {w}×{h} é múltiplo de 64 com proporção {ar_w}:{ar_h} — padrão de modelos de diffusion")
        except Exception:
            pass
        return findings

    # ─────────────────────────────────────────────────────────────────────────
    # ANÁLISE PRINCIPAL (combina tudo)
    # ─────────────────────────────────────────────────────────────────────────
    @staticmethod
    def analyze(image_path: str) -> dict:
        score = 0
        reasons = []
        hidden_codes = []

        # ── 1. Metadados EXIF / XMP / PNG
        meta_findings = AIDetector.check_all_metadata_fields(image_path)
        if meta_findings:
            score += min(len(meta_findings) * 25, 80)
            reasons.extend(meta_findings)
            hidden_codes.extend(meta_findings)

        # ── 2. Varredura Binária Profunda
        binary_findings = AIDetector.deep_binary_scan(image_path)
        if binary_findings:
            score += min(len(binary_findings) * 20, 80)
            for f in binary_findings[:5]:  # limita para não sobrecarregar
                reasons.append(f)
                hidden_codes.append(f)

        # ── 3. C2PA / Content Credentials
        c2pa_findings = AIDetector.check_c2pa(image_path)
        if c2pa_findings:
            score += 70
            reasons.extend(c2pa_findings)
            hidden_codes.extend(c2pa_findings)

        # ── 4. Chunks PNG
        png_findings = AIDetector.analyze_png_chunks(image_path)
        if png_findings:
            score += min(len(png_findings) * 30, 80)
            reasons.extend(png_findings)
            hidden_codes.extend(png_findings)

        # ── 5. Análise Estatística (LSB, DCT, Laplacian)
        stats = AIDetector.analyze_statistical_artifacts(image_path)
        if stats["notes"]:
            score += min(len(stats["notes"]) * 20, 60)
            reasons.extend(stats["notes"])

        # ── 6. Resolução
        res_findings = AIDetector.check_ai_resolution(image_path)
        if res_findings:
            score += 40
            reasons.extend(res_findings)

        # Clamp
        score = min(score, 100)

        probability = "Baixa"
        if score >= 70:
            probability = "Alta"
        elif score >= 35:
            probability = "Média"

        # Recupera software para exibição
        meta = AIDetector.extract_metadata(image_path)

        return {
            "ai_probability": probability,
            "ai_score": int(score),
            "reasons": list(dict.fromkeys(reasons)),  # deduplica preservando ordem
            "hidden_codes": list(dict.fromkeys(hidden_codes)),
            "metadata_software": meta.get("software") or "Nenhum",
            "statistical_analysis": {
                "lsb_uniformity": float(stats.get("lsb_uniformity", 0)),
                "dct_score": float(stats.get("dct_score", 0)),
                "laplacian_variance": float(stats.get("laplacian_variance", 0)),
            }
        }
